/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:19397f46-7b3f-4831-9955-05f5f030f401",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_H4t58UC0Q",
    "aws_user_pools_web_client_id": "7k73ifbj9uo7i5ad2ogbopg0qu",
    "oauth": {}
};


export default awsmobile;
